### ISSUE TITLE
Fatal error: Uncaught Error: Class 'db\QueryBuilder\QueryBuilder' not found

### ISSUE THREAD

**Issue by aneesdhansey** [askello/opencart-query-builder#4]
I'm using the opencart query builder in one of my projects and it works fine on my local machine (Windows).
But as soon as I deploy the project to my hosting server (linux/cpanel), I get this error on startup, in the framework.php file.

> Fatal error: Uncaught Error: Class 'db\QueryBuilder\QueryBuilder' not found

I've searched through various stackoverflow questions about issues with namespaces but I can't seem to get on the right track.

This is the part of the code thats causing the problem:
`$registry->set('db', new db\QueryBuilder\QueryBuilder($registry->get('db')));`
As soon as I comment this out, it works properly.

Any help would be appreciated.

Thanks.

**Comment by askello** [comment]
Hello. Thanks for the report. I will try to find the problem and fix it

**Comment by askello** [comment]
Fixed it. Linux OS filesystem is case sensitive, and opencart autoloader converts all class paths to lower case, so I had to rename everything to lowercase too.

**Comment by aneesdhansey** [comment]
Thanks a lot!
