### ISSUE TITLE
 Call to undefined method parseCondition()

### ISSUE THREAD

**Issue by YRN** [askello/opencart-query-builder#7]
when inner join using this query builder appear this error

**Comment by askello** [comment]
Hi. Thanks for your notice, and sorry for that =) Fixed it, enjoy!

**Comment by YRN** [comment]
thanks for the response, so i should pull your code?

**Comment by askello** [comment]
yes

**Comment by YRN** [comment]
thanks you sirr

**Comment by askello** [comment]
you're welcome
